const mockData = [
  {
    id: 1,
    weight_name: "Queen Elizabeth",
    media_type: "audio",
    public_bucket_path: "/path/to/audio.mp3",
    favorites: 150,
    liked: true,
  },
  {
    id: 2,
    weight_name: "House",
    media_type: "image",
    public_bucket_path: "/images/dummy-image.jpg",
    favorites: 200,
    liked: false,
  },
  {
    id: 3,
    weight_name: "3",
    media_type: "audio",
    public_bucket_path: "/path/to/image.jpg",
    favorites: 200,
    liked: false,
  },
  {
    id: 4,
    weight_name: "4",
    media_type: "audio",
    public_bucket_path: "/path/to/audio.mp3",
    favorites: 150,
    liked: true,
  },
  {
    id: 5,
    weight_name: "5",
    media_type: "image",
    public_bucket_path: "/images/dummy-image.jpg",
    favorites: 200,
    liked: false,
  },
  {
    id: 6,
    weight_name: "Superman",
    media_type: "audio",
    public_bucket_path: "/path/to/image.jpg",
    favorites: 200,
    liked: false,
  },
  {
    id: 4,
    weight_name: "4",
    media_type: "audio",
    public_bucket_path: "/path/to/audio.mp3",
    favorites: 150,
    liked: true,
  },
  {
    id: 4,
    weight_name: "4",
    media_type: "audio",
    public_bucket_path: "/path/to/audio.mp3",
    favorites: 150,
    liked: true,
  },
  {
    id: 4,
    weight_name: "4",
    media_type: "audio",
    public_bucket_path: "/path/to/audio.mp3",
    favorites: 150,
    liked: true,
  },
  {
    id: 4,
    weight_name: "4",
    media_type: "audio",
    public_bucket_path: "/path/to/audio.mp3",
    favorites: 150,
    liked: true,
  },
];

export default mockData;
