const mockData = [
  {
    id: 1,
    weight_name: "Queen Elizabeth",
    media_type: "audio",
    public_bucket_path: "/path/to/audio.mp3",
    favorites: 150,
    liked: true,
  },
  {
    id: 2,
    weight_name: "House",
    media_type: "image",
    public_bucket_path: "/images/dummy-image.jpg",
    favorites: 200,
    liked: false,
  },
  {
    id: 3,
    weight_name: "Ronaldo",
    media_type: "audio",
    public_bucket_path: "/path/to/audio.mp3",
    favorites: 200,
    liked: false,
  },
  {
    id: 4,
    weight_name: "Messi",
    media_type: "audio",
    public_bucket_path: "/path/to/audio.mp3",
    favorites: 150,
    liked: true,
  },
  {
    id: 5,
    weight_name: "Ash Ketchum",
    media_type: "image",
    public_bucket_path: "/images/dummy-image-2.jpg",
    favorites: 200,
    liked: false,
  },
  {
    id: 6,
    weight_name: "Superman",
    media_type: "audio",
    public_bucket_path: "/path/to/image.jpg",
    favorites: 200,
    liked: false,
  },
  {
    id: 7,
    weight_name: "Son Goku",
    media_type: "audio",
    public_bucket_path: "/path/to/audio.mp3",
    favorites: 150,
    liked: true,
  },
  {
    id: 8,
    weight_name: "Image Test",
    media_type: "image",
    public_bucket_path: "/images/dummy-image-3.jpg",
    favorites: 150,
    liked: true,
  },
  {
    id: 9,
    weight_name: "Monokuma",
    media_type: "audio",
    public_bucket_path: "/path/to/audio.mp3",
    favorites: 150,
    liked: true,
  },
  {
    id: 10,
    weight_name: "Image Test",
    media_type: "image",
    public_bucket_path: "/images/dummy-image-4.jpg",
    favorites: 150,
    liked: true,
  },
];

export default mockData;
