import { signal } from "@preact/signals-core";
import { AssetType, MediaItem } from "~/pages/PageEnigma/models";
import * as uuid from "uuid";

export const animationItems = signal<MediaItem[]>([
  {
    version: 1,
    media_id: "m_yzreg1494d08aepezj74607d2ascep",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Sit",
    thumbnail: "/resources/characters/img04.png",
    isMine: true,
  },
  {
    version: 1,
    media_id: "m_qepzjytd4ahd5askdt2ngrwzj2aa3f",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Idle",
    thumbnail: "/resources/characters/img07.png",
    isBookmarked: true,
  },
  {
    version: 1,
    media_id: "m_s7d4ems68sb2vqj4pdje1rc15q3ycp",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Walk",
    thumbnail: "/resources/characters/img07.png",
  },
  {
    version: 1,
    media_id: "m_v06h821hj4dvst0mzm575jdka31f41",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Punch",
    thumbnail: "/resources/characters/img08.png",
  },
  {
    version: 1,
    media_id: "m_q92keqa05gds69zyd8mkep7z9338t8",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Jump",
    thumbnail: "/resources/characters/img06.png",
  },
  {
    version: 1,
    media_id: "m_0qmgsyxh5ng9c9ac3m0snzdqqs5q60",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Dance",
    thumbnail: "/resources/characters/img11.png",
  },
  {
    version: 1,
    media_id: "m_4ydax69ystd9tzq8m714jrdqcc6nvw",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Jump Forward",
    thumbnail: "/resources/characters_gif/Jump Forward.gif",
  },
  {
    version: 1,
    media_id: "m_rhscc6zrt9sftpwvx2xyf965a5mh4p",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Tonic Seizure",
    thumbnail: "/resources/characters_gif/Tonic Seizure.gif",
  },
  {
    version: 1,
    media_id: "m_xd30y703zeqke26j7v9qh5cnzwn0h9",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Ginga Variation 3",
    thumbnail: "/resources/characters_gif/Ginga Variation 3.gif",
  },
  {
    version: 1,
    media_id: "m_pqvz4a5twvfe00x20hv9qx1c3vd35n",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Crouch Running",
    thumbnail: "/resources/characters_gif/Crouch Running.gif",
  },
  {
    version: 1,
    media_id: "m_b5nn2315kwanbn9tj8v6jwbkycysmg",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Strafing Jump",
    thumbnail: "/resources/characters_gif/Strafing Jump.gif",
  },
  {
    version: 1,
    media_id: "m_jggmpzjvy68pyt8v4n3nxqfy80kqbg",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Texting",
    thumbnail: "/resources/characters_gif/Texting.gif",
  },
  {
    version: 1,
    media_id: "m_xezj4qpe5mav3gv4vbfjksvhctb365",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Pushing",
    thumbnail: "/resources/characters_gif/Pushing.gif",
  },
  {
    version: 1,
    media_id: "m_3zd4v5hvk36xjm4gt0bhvtqxy6jzfa",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Standing Idle To Crouch",
    thumbnail: "/resources/characters_gif/Standing Idle To Crouch.gif",
  },
  {
    version: 1,
    media_id: "m_hre1hae6yvj4wyy3xkzc2a12ytt1dq",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Fight Idle To Standing Idle",
    thumbnail: "/resources/characters_gif/Fight Idle To Standing Idle.gif",
  },
  {
    version: 1,
    media_id: "m_4fyxtbk4fxz312cc6y4bs5y739x4dc",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Texting While Standing",
    thumbnail: "/resources/characters_gif/Texting While Standing.gif",
  },
  {
    version: 1,
    media_id: "m_zxdethnpahecz2v0nj0k4xjehdb3ne",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Getting Bit",
    thumbnail: "/resources/characters_gif/Getting Bit.gif",
  },
  {
    version: 1,
    media_id: "m_6cre8q6csjj6cs41esa3qjt3kb0aen",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Female Laying Pose",
    thumbnail: "/resources/characters_gif/Female Laying Pose.gif",
  },
  {
    version: 1,
    media_id: "m_m27a9jwh96xe270pgxcjwg88c0a01j",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Twist Dance",
    thumbnail: "/resources/characters_gif/Twist Dance.gif",
  },
  {
    version: 1,
    media_id: "m_9ejtr55r3s84gpek5wxn1v4apcjff7",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Femme Peek Around Corner",
    thumbnail: "/resources/characters_gif/Femme Peek Around Corner.gif",
  },
  {
    version: 1,
    media_id: "m_1cvqm136nsjgnkzst9rc4w5rgfefxj",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Sword And Shield Casting",
    thumbnail: "/resources/characters_gif/Sword And Shield Casting.gif",
  },
  {
    version: 1,
    media_id: "m_hndk99w0knxmxvm23vshyybwace9hx",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Breakdance Ready",
    thumbnail: "/resources/characters_gif/Breakdance Ready.gif",
  },
  {
    version: 1,
    media_id: "m_30ak4bj738gs8eax3bz8b7nyg55x4d",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Sitting Yell",
    thumbnail: "/resources/characters_gif/Sitting Yell.gif",
  },
  {
    version: 1,
    media_id: "m_hj31108d09zsvsv2r8rbb3j9vkas06",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Uppercut",
    thumbnail: "/resources/characters_gif/Uppercut.gif",
  },
  {
    version: 1,
    media_id: "m_y5q63v1j8k0r72zc18ppnpgw1gga4n",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Female Standing Pose",
    thumbnail: "/resources/characters_gif/Female Standing Pose.gif",
  },
  {
    version: 1,
    media_id: "m_fzsrqv5bcyk4fq6ewx93sztbxgcnf2",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Breakdance Uprock Var 1",
    thumbnail: "/resources/characters_gif/Breakdance Uprock Var 1.gif",
  },
  {
    version: 1,
    media_id: "m_8bsmytdf4ak7kazkj78sfexpx6wvwy",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Standard Walk",
    thumbnail: "/resources/characters_gif/Standard Walk.gif",
  },
  {
    version: 1,
    media_id: "m_h1a1kxdme2msze57cwf6j4zqj2gxp1",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Rifle Pull Out",
    thumbnail: "/resources/characters_gif/Rifle Pull Out.gif",
  },
  {
    version: 1,
    media_id: "m_hw99268jayaw8nxy7nf9hvn4ep88xb",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Sword And Shield Jump",
    thumbnail: "/resources/characters_gif/Sword And Shield Jump.gif",
  },
  {
    version: 1,
    media_id: "m_3rrqez1yb8efm7wne4m9kbaeda1270",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Baseball Bunt",
    thumbnail: "/resources/characters_gif/Baseball Bunt.gif",
  },
  {
    version: 1,
    media_id: "m_42h0gejk68p1ean0qqhwz3ktvb0nd1",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Strafing",
    thumbnail: "/resources/characters_gif/Strafing.gif",
  },
  {
    version: 1,
    media_id: "m_19cz9a2wdgbpn99tx9gdtw3t7t1k6h",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Sneaking Forward",
    thumbnail: "/resources/characters_gif/Sneaking Forward.gif",
  },
  {
    version: 1,
    media_id: "m_2s92ajhzjwq4x290m2f0bst57p67g7",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Skinning Test",
    thumbnail: "/resources/characters_gif/Skinning Test.gif",
  },
  {
    version: 1,
    media_id: "m_t4nhndxppb8807pq5d5t2y3ck2dzws",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Female Dance Pose",
    thumbnail: "/resources/characters_gif/Female Dance Pose.gif",
  },
  {
    version: 1,
    media_id: "m_0sm2ycm3napvsqhgbm06nkv6x48vqj",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Right Strafe Walking",
    thumbnail: "/resources/characters_gif/Right Strafe Walking.gif",
  },
  {
    version: 1,
    media_id: "m_xvq7ybyjmwsebhxw31kxn5v0pksjvf",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Laying Breathless",
    thumbnail: "/resources/characters_gif/Laying Breathless.gif",
  },
  {
    version: 1,
    media_id: "m_vsfkdm3f1nkerwakfcq7xb1kscawkb",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Box Jump",
    thumbnail: "/resources/characters_gif/Box Jump.gif",
  },
  {
    version: 1,
    media_id: "m_vrwzar5kwm2p1crtcxvxqmpxv7dt9x",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Orc Walk",
    thumbnail: "/resources/characters_gif/Orc Walk.gif",
  },
  {
    version: 1,
    media_id: "m_f6zvavya6n9zdkhd4nzh5s9wj39zwn",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Run Look Back",
    thumbnail: "/resources/characters_gif/Run Look Back.gif",
  },
  {
    version: 1,
    media_id: "m_gb489zh9dn4h41c8gdna6jgcvdpxjf",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Standing Torch Jump",
    thumbnail: "/resources/characters_gif/Standing Torch Jump.gif",
  },
  {
    version: 1,
    media_id: "m_p3fzg4p0d46xwq2qk0chrvmht4xx9v",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Lengthy Head Nod",
    thumbnail: "/resources/characters_gif/Lengthy Head Nod.gif",
  },
  {
    version: 1,
    media_id: "m_65m8gaaxhmsgzjg4eye7v4gkpvdjwq",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Pistol Run Backward Arc",
    thumbnail: "/resources/characters_gif/Pistol Run Backward Arc.gif",
  },
  {
    version: 1,
    media_id: "m_aazz0c3e1ygdawhny6vxm9yyw0t00d",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Right Hook",
    thumbnail: "/resources/characters_gif/Right Hook.gif",
  },
  {
    version: 1,
    media_id: "m_1c7enn6wzsb44qw26azpb9ewecmja8",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Great Sword Impact",
    thumbnail: "/resources/characters_gif/Great Sword Impact.gif",
  },
  {
    version: 1,
    media_id: "m_xy9p9x6bnq0nc4tb7ajb7hh91hk1ec",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Zombie Biting",
    thumbnail: "/resources/characters_gif/Zombie Biting.gif",
  },
  {
    version: 1,
    media_id: "m_7e2gmcwy1t6bbkwetn1ad7fmtg15ek",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Leaning",
    thumbnail: "/resources/characters_gif/Leaning.gif",
  },
  {
    version: 1,
    media_id: "m_24zpmn5eqemy6sjeky2cc5e73axrk2",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Standing Torch To Crouch Torch",
    thumbnail: "/resources/characters_gif/Standing Torch To Crouch Torch.gif",
  },
  {
    version: 1,
    media_id: "m_5p7ev3x77vgmt14f5wb6verm6r8dcm",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Action Idle To Fight Idle",
    thumbnail: "/resources/characters_gif/Action Idle To Fight Idle.gif",
  },
  {
    version: 1,
    media_id: "m_3dkcn3c1j160xvbe1haqprmsb566qg",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Corkscrew Evade",
    thumbnail: "/resources/characters_gif/Corkscrew Evade.gif",
  },
  {
    version: 1,
    media_id: "m_x8kndshp2psy8cx7r4z13m3hkp7t1t",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Catwalk Walk Forward Crossed",
    thumbnail: "/resources/characters_gif/Catwalk Walk Forward Crossed.gif",
  },
  {
    version: 1,
    media_id: "m_zhp9kzjwq1ek1618kzk88a0c7nv4y4",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Look Around",
    thumbnail: "/resources/characters_gif/Look Around.gif",
  },
  {
    version: 1,
    media_id: "m_6p1412cnc40ht8ntx97jdxa1vtyyps",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Zombie Stand Up",
    thumbnail: "/resources/characters_gif/Zombie Stand Up.gif",
  },
  {
    version: 1,
    media_id: "m_b1vkd8hj22mnhgsxx00vg8aha8pxda",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Convulsing",
    thumbnail: "/resources/characters_gif/Convulsing.gif",
  },
  {
    version: 1,
    media_id: "m_4fdvb74csta9nw3rx1he6hjcpvm6tc",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Pistol Whip",
    thumbnail: "/resources/characters_gif/Pistol Whip.gif",
  },
  {
    version: 1,
    media_id: "m_g4qk6cn80yttm4vj5e5cq2yy7wa20j",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Mutant Idle",
    thumbnail: "/resources/characters_gif/Mutant Idle.gif",
  },
]);

export const audioItems = signal<MediaItem[]>([
  {
    version: 1,
    media_id: "m_403phjvjkbbaxxbz8y7r6qjay07mfd",
    type: AssetType.AUDIO,
    length: 25,
    name: "Talk (Demo Sounds)",
    thumbnail: "/resources/placeholders/audio_placeholder.png",
  },
  {
    version: 1,
    media_id: "m_w5nn3kjh1fbkmjrdac5b2qaba0pmyt",
    type: AssetType.AUDIO,
    length: 25,
    name: "NCS Song",
    thumbnail: "/resources/placeholders/audio_placeholder.png",
  },
]);

export const cameraItems = signal<MediaItem[]>([
  {
    version: 1,
    media_id: uuid.v4(),
    type: AssetType.CAMERA,
    name: "Portrait Zoom Out",
    thumbnail: "/resources/placeholders/placeholder.png",
  },
  {
    version: 1,
    media_id: uuid.v4(),
    type: AssetType.CAMERA,
    name: "Pan Left and Right",
    thumbnail: "/resources/placeholders/placeholder.png",
  },
]);

export const characterItems = signal<MediaItem[]>([
  {
    version: 1,
    media_id: "m_fmxy8wjnep1hdaz7qdg4n7y15d2bsp",
    type: AssetType.CHARACTER,
    name: "Shrek",
    thumbnail: "/resources/placeholders/placeholder.png",
  },
  {
    version: 1,
    media_id: "m_9f3d3z94kk6m25zywyz6an3p43fjtw",
    type: AssetType.CHARACTER,
    name: "Stick Man",
    thumbnail: "/resources/placeholders/placeholder.png",
  },
  {
    version: 1,
    media_id: "m_r7w1tmkx2jg8nznr3hyzj4k6zhfh7d ",
    type: AssetType.CHARACTER,
    name: "Female Doll",
    thumbnail: "/resources/characters/img03.png",
  },
  {
    version: 1,
    media_id: "m_9sqg0evpr23587jnr8z3zsvav1x077 ",
    type: AssetType.CHARACTER,
    name: "Male Doll",
    thumbnail: "/resources/characters/img03.png",
  },
  {
    version: 1,
    media_id: "m_pwtk45wsfr5z2bavmwxh2efnwvh4rr ",
    type: AssetType.CHARACTER,
    name: "Story Girl",
    thumbnail: "/resources/characters/img13.png",
  },
  {
    version: 1,
    media_id: "m_ffhbh6zgjhxxgeg1r3tsj2kqrqqana",
    type: AssetType.CHARACTER,
    name: "Waifu H",
    thumbnail: "/resources/characters/img14.png",
  },
  {
    version: 1,
    media_id: "m_qfqw9e5kz0b7kspbwcc3c9y7pym97q",
    type: AssetType.CHARACTER,
    name: "Skibidi Toilet",
    thumbnail: "/resources/characters/img15.png",
  },
  {
    version: 1,
    media_id: "m_ecfxa94v4ftvh58hv7se3qqy8a385n",
    type: AssetType.CHARACTER,
    name: "Pop",
    thumbnail: "/resources/placeholders/placeholder.png",
  }
]);

export const objectItems = signal<MediaItem[]>([
  {
    version: 1,
    media_id: "m_0xfrmekc56satjxn66wt6c9dkw7dxe",
    type: AssetType.OBJECT,
    name: "Pikachu Statue",
    thumbnail: "/resources/placeholders/placeholder.png",
  },
  {
    version: 1,
    media_id: "m_4d2s2q1xy9m1xncppr3gf9ne6bm2m0",
    type: AssetType.OBJECT,
    name: "Moon",
    thumbnail: "/resources/objects/moon.png",
  },
  {
    version: 1,
    media_id: "m_t0s6gbvfp78rvc0sd6129za41crr9d",
    type: AssetType.OBJECT,
    name: "Crown",
    thumbnail: "/resources/objects/crown.png",
  },
  {
    version: 1,
    media_id: "m_zp0zykww0k7ka2zagg3q3pb9t123k4",
    type: AssetType.OBJECT,
    name: "Sakura Tree",
    thumbnail: "/resources/objects/sakura.png",
  },
]);

// In the future these will have shape id's
export const shapeItems = signal<MediaItem[]>([
  {
    version: 1,
    media_id: "Box",
    type: AssetType.SHAPE,
    name: "Cube",
    thumbnail: "/resources/shapes/cube.png",
  },
  {
    version: 1,
    media_id: "Cylinder",
    type: AssetType.SHAPE,
    name: "Cylinder",
    thumbnail: "/resources/shapes/cylinder.png",
  },
  {
    version: 1,
    media_id: "Donut",
    type: AssetType.SHAPE,
    name: "Donut",
    thumbnail: "/resources/shapes/donut.png",
  },
  {
    version: 1,
    media_id: "Sphere",
    type: AssetType.SHAPE,
    name: "Sphere",
    thumbnail: "/resources/shapes/sphere.png",
  },
]);
