use actix_cors::Cors;

pub fn add_development_only(cors: Cors) -> Cors {
  cors
      // Local Development (Localhost)
      .allowed_origin("http://localhost:3000")
      .allowed_origin("http://localhost:4200")
      .allowed_origin("http://localhost:5555")
      .allowed_origin("http://localhost:7000")
      .allowed_origin("http://localhost:7001")
      .allowed_origin("http://localhost:7002")
      .allowed_origin("http://localhost:7003")
      .allowed_origin("http://localhost:7004")
      .allowed_origin("http://localhost:7005")
      .allowed_origin("http://localhost:7006")
      .allowed_origin("http://localhost:7007")
      .allowed_origin("http://localhost:7008")
      .allowed_origin("http://localhost:7009")
      .allowed_origin("http://localhost:8000")
      .allowed_origin("http://localhost:8080")
      .allowed_origin("http://localhost:12345")
      .allowed_origin("http://localhost:54321")
      // Local Development (JungleHorse)
      .allowed_origin("http://api.jungle.horse")
      .allowed_origin("http://jungle.horse")
      .allowed_origin("http://jungle.horse:12345")
      .allowed_origin("http://jungle.horse:7000")
      .allowed_origin("http://obs.jungle.horse")
      .allowed_origin("http://ws.jungle.horse")
      .allowed_origin("https://api.jungle.horse")
      .allowed_origin("https://jungle.horse")
      .allowed_origin("https://obs.jungle.horse")
      .allowed_origin("https://ws.jungle.horse")
}

