npmScopes:
 fortawesome:
   npmAlwaysAuth: true
   npmRegistryServer: "https://npm.fontawesome.com/"
   # NB: THIS IS A SECRET. OH MY GOD, WE'RE COMMITTING IT TO GIT.
   # DON'T DO THIS FOR ANY OTHER SECRETS.
   npmAuthToken: "104779DB-FD41-4BEA-BDB4-B1845D758A79"
