#!/bin/bash

# These secrets aren't dangerous to include here (except if stolen,
# possible to generate charges against our account).
# Ultimately, translations are generated by engineering PRs and
# suspicous/dubious changes should be watched for by engineers.
locize sync \
  --api-key f918942b-4a56-49cc-af58-05fc83a9bd75 \
  --project-id 7a6e6c67-300c-4707-8d98-6efd1abce3c4 \
  --path packages/fakeyou.com/public/locales

