# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/audio.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/audio.proto',
  package='voder_audio',
  syntax='proto3',
  serialized_pb=_b('\n\x12protos/audio.proto\x12\x0bvoder_audio\"h\n\x12VocodeAudioRequest\x12\x15\n\rinteger_audio\x18\x01 \x03(\x05\x12\x13\n\x0b\x66loat_audio\x18\x02 \x03(\x02\x12\x13\n\x0bskip_vocode\x18\x03 \x01(\x08\x12\x11\n\ttest_name\x18\x04 \x01(\t\"T\n\x13VocodeAudioResponse\x12\x15\n\rinteger_audio\x18\x01 \x03(\x05\x12\x13\n\x0b\x66loat_audio\x18\x02 \x03(\x02\x12\x11\n\ttest_name\x18\x03 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VOCODEAUDIOREQUEST = _descriptor.Descriptor(
  name='VocodeAudioRequest',
  full_name='voder_audio.VocodeAudioRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='integer_audio', full_name='voder_audio.VocodeAudioRequest.integer_audio', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float_audio', full_name='voder_audio.VocodeAudioRequest.float_audio', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skip_vocode', full_name='voder_audio.VocodeAudioRequest.skip_vocode', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='test_name', full_name='voder_audio.VocodeAudioRequest.test_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=139,
)


_VOCODEAUDIORESPONSE = _descriptor.Descriptor(
  name='VocodeAudioResponse',
  full_name='voder_audio.VocodeAudioResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='integer_audio', full_name='voder_audio.VocodeAudioResponse.integer_audio', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float_audio', full_name='voder_audio.VocodeAudioResponse.float_audio', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='test_name', full_name='voder_audio.VocodeAudioResponse.test_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=225,
)

DESCRIPTOR.message_types_by_name['VocodeAudioRequest'] = _VOCODEAUDIOREQUEST
DESCRIPTOR.message_types_by_name['VocodeAudioResponse'] = _VOCODEAUDIORESPONSE

VocodeAudioRequest = _reflection.GeneratedProtocolMessageType('VocodeAudioRequest', (_message.Message,), dict(
  DESCRIPTOR = _VOCODEAUDIOREQUEST,
  __module__ = 'protos.audio_pb2'
  # @@protoc_insertion_point(class_scope:voder_audio.VocodeAudioRequest)
  ))
_sym_db.RegisterMessage(VocodeAudioRequest)

VocodeAudioResponse = _reflection.GeneratedProtocolMessageType('VocodeAudioResponse', (_message.Message,), dict(
  DESCRIPTOR = _VOCODEAUDIORESPONSE,
  __module__ = 'protos.audio_pb2'
  # @@protoc_insertion_point(class_scope:voder_audio.VocodeAudioResponse)
  ))
_sym_db.RegisterMessage(VocodeAudioResponse)


# @@protoc_insertion_point(module_scope)
