export enum ToolbarMainButtonNames {
  MENU = "MENU",
  SELECT_ONE = "SELECT_ONE",
  SELECT_AREA = "SELECT_AREA",
  CHANGE_CAMERA_ORIENTATION = "CHANGE_CAMERA_ORIENTATION",
  AI_STYLIZE = "AI_STYLIZE",
  UNDO = "UNDO",
  REDO = "REDO",
  SAVE = "SAVE",
  DOWNLOAD = "DOWNLOAD",
}
