export enum ToolbarMainButtonNames {
  MENU = "MENU",
  SELECT = "SELECT",
  CHANGE_CAMERA_ORIENTATION = "CHANGE_CAMERA_ORIENTATION",
  AI_STYLIZE = "AI_STYLIZE",
  UNDO = "UNDO",
  REDO = "REDO",
  SAVE = "SAVE",
  DOWNLOAD = "DOWNLOAD",
}
