export enum ToolbarMainButtonNames {
  MENU = "MENU",
  SELECT = "SELECT",
  ADD_TEXT = "ADD_TEXT",
  ADD_IMAGE = "ADD_IMAGE",
  ADD_VIDEO = "ADD_VIDEO",
  // CHANGE_CAMERA_ORIENTATION = "CHANGE_CAMERA_ORIENTATION",
  AI_STYLIZE = "AI_STYLIZE",
  UNDO = "UNDO",
  REDO = "REDO",
  SAVE = "SAVE",
  DOWNLOAD = "DOWNLOAD",
}
