export enum ToolbarImageButtonNames {
  MOVE = "MOVE",
  ROTATE = "ROTATE",
  AI_STYLIZE = "AI_STYLIZE",
  DELETE = "DELETE",
  MOVE_LAYER_UP = "MOVE_LAYER_UP",
  MOVE_LAYER_DOWN = "MOVE_LAYER_DOWN",
}
