
const SENTENCES : string[] = [
  "don't murder the poor people",
  "hillary destroys all the good things",
  "hillary is my favorite person in the world",
  "i feel that war is a beautiful thing",
  "i must be going crazy",
  "i needed my mother and father that day",
  "i remember when I was only fifty seven years of age",
  "i saw children dying every way i look",
  "i think your parents are absolutely stupid",
  "i want all of your money immediately after this",
  "i want to come in first place",
  "i will always think you are stupid",
  "i'm smarter than your children",
  "i'm the president of reality space and the internet",
  "it was a long time ago when hillary and bill got married",
  "it's really amazing how dumb you are",
  "just see the chaos i can create",
  "let's count some numbers",
  "let's make america great again",
  "our civilization is better than the one they have",
  "stop it",
  "that man has taken all of my money",
  "the total chaos and destruction is beautiful",
  "there are countless children i needed to take from their countries",
  "there are great images on the internet you know",
  "this is the opportunity to take from the rich",
  "we are all victims of harassment and abuse",
  "what are you doing to those children",
  "you and i are the same",
  "you are all fools and i hate you",
  "you fricken moron",
  "that has increased my interest",
  "your country is tragic and terrible",
];

export = SENTENCES;

