export enum TabTitles {
  ANIMATION = "Animation",
  AUDIO = "Audio",
  CHARACTERS = "Character",
  GROUP_ANIME = "Anime Characters & Animations",
  GROUP_CARTOONS = "Cartoon Characters & Animations",
  EXPRESSIONS = "Facial Expression",
  OBJECTS = "Set Dressings",
  OBJECTS_CREATURES = "Creatures",
  OBJECTS_SETS = "Film Sets",
  PLANES = "Image & Video Panels",
  PLANES_IMAGE = "Image Panels",
  PLANES_VIDEO = "Video Panels",
  SKYBOXES = "Skyboxes",
  STYLIZE = "AI Stylize",
}
