import { ArtStyle } from "~/pages/PageEnigma/js/api_manager";

export const RandomTextsPositive: Record<ArtStyle, string[]> = {
  [ArtStyle.AnimeStandard]: [
    "1girl, beach, sea, large white hat, long white dress, long hair, smiling",
    "woman, solo, forest, mountains on background, blue sky, white clouds, seductive smile, pink hair,  hair ornament, japanese clothes, detached sleeves, wide sleeves, jewelry, earrings",
    "solo, male focus, 1boy, son gohan, super saiyan, (aura, angry, ),  (fighting stance:1.2), blonde hair,  (torn clothes:0.8), dougi, canyon, beautiful face",
    "marketplace style, village, crowd, people, standing, building, pottery, engraving,  city of the souls, a portrait of waterfall tree, clouds, lake,  enchanted forest, water bodies, flower garden, surreal animals, fantasy, dream, dreamy, sunny, pathway",
    "small creature, animal focus, on tree, forest, close up, detailed, light particles",
  ],
  [ArtStyle.Anime2DFlat]: [
    "1boy, solo, large wooden ship on background, fire, flame, solo black hair, laughing, power overflow, overcharge, cloak, hero pose",
    "nature shot with wide shot of a dark jungle scene,face of a black-leopard hiding between the bushes,hunting,nightfall,dimmly lit,intense gaze,tension",
    "sailboat in the ocean with a moon in the sky, unreal engine fantasy art, beautiful retro art, fantasy forest landscape, cinematic silk road landscape",
    "polarized, at night, roof of ancient Church, burning city, Red Moon, dark magic, grotesque creatures, punk aesthetic, dark fantasy ,grim landscapes, vibrant Deep colorful, heroes skirmish monstrous foes in a setting where rebellion, decay, and mysticism intertwine",
    "a girl in pirate uniform sits in the captain's cabin, perfect face, pirate hat, gold coins piled on the wooden table, dim candlelight, upper body",
  ],
  [ArtStyle.AnimeGhibli]: [
    "ghibli style, san \\(mononoke hime\\), 1girl, armlet, bangs, black hair, black undershirt, breasts, cape, circlet, earrings, facepaint, (bird view,on top of mountain, forest from above, from above, far landscape, ) fur cape, green eyes, jewelry, looking at viewer, medium breasts, nature, necklace, outdoors, parted bangs, shirt, short hair, sleeveless, sleeveless shirt, solo, tooth necklace, tree, upper body, white shirt",
    "portrait of a poisonous frog, in forest, close up, reflection, lightning, leafs",
    "landscape, sun down, red sky, saturated colors, field of roses, cottage in the background, Watercolor",
    "two laggard cops arresting ridiculously chubby enormous cat",
    "1girl, flowers, blue hair, blue eyes",
  ],
  [ArtStyle.Cartoon3D]: [
    "princess, long hair, solo",
    "an adorable fluffy tiny mouse with big ears, in a field, grass, Fairytale cabin, laugh",
    "water elements,beautiful expressive face, underwater, extremely detailed, beautiful underwater dragon creature, no humans, extremely detailed scales, seaweed mane, fishtail, beautiful eyes, moonlight, realistic, high quality, detailed, fantasy dark cave background, sparkling water, dark shadows, glowing in the dark, bright colors, high contrast, dark background, vivid lighting",
    "black background, apocalyptic subway, old bed, old fridge, old stove, old tv, dark, sewer, melancholic, watercolor, bold pencil outline, professional art, high detail, intricate detail, high resolution, steam",
    "(no humans), scenery, landscape, ocean, sea, palm tree",
  ],
  [ArtStyle.Anime2_5D]: [
    "elf girl, wings, pixy, large flower, magic, fairy, fairytale, stars, blessing, sparks",
    "most cute fantasy animals of the world,different species,big eyes,very fluffy",
    "(a giant battle cyborg:1.1), angry, fullmetal, robotic, mechanical parts, (burning city background:1.2), slate atmosphere",
    "there is a strange plants and flower grow in the Venus soil, yellow environment, bloom, flowers bloom, yellow particles, yellow spark, surrounding by yellow dust, sun ray, yellow atmosphere, realistic",
    "Capture the awe-inspiring sight of a colossal, mystical Chinese eastern dragon weaving through a labyrinth of urban buildings, its luminous, semi-transparent form illuminated against the night sky",
  ],
  [ArtStyle.Realistic1]: [
    "fashion photography picture of a woman wearing a black turtleneck and white pants with a brown belt, outdoors at an abandoned mall, standing on an escalator",
    "polaroid photo, night photo, photo of a woman wearing a dress with a fluffy fur coat, fur-trimmed coat, (she has long silver straight hair and blue eyes), pale skin, bokeh, motion blur, film grain, light leaks, tokyo cityscape, black dress",
    "a sportscar on fire at night in the middle of an abandoned field, polaroid photo, liminal",
    "a professional photo of a cat sitting on a windowsill, dark theme, it's raining outside",
    "top-down view of a cityscape at night, blurring lights, bokeh, professional photo, hq, 4k",
  ],
  [ArtStyle.Realistic2]: [
    "a witch casting magic in a forest at night, sharp focus, dramatic, cinematic lighting, upper body, realistic, looking at viewer, smirk",
    "headshot profile of a woman with elf ears, indoors in a fashion studio, long silver curly hair, gentle green hazel eyes, lace dress, wedding dress",
    "a knight in the middle of a rainstorm, lightning, thunder clouds, helmet, reflective shiny knight armor, cinematic angle, dramatic, dark theme",
    "a cat laying down and sleeping on a pillow, cottage, cottagecore, potted plants, vines, comfy indoors cottage, windows, lightrays, sunlight, light depth of field, yellow eyes, black fur",
  ],
  [ArtStyle.PopArt]: [
    "pop art, 1girl, solo,  hugging cat, long hair, black hair, bare shoulders, simple lines, flat color,",
    "dance of death, figures entwined in a macabre ballet under a glowing moon against the backdrop of a night sky, shadows casting long on the abandoned landscape",
    "Monstrous blizzard with the fierce face of a bear, engulfed in whiteout conditions, swirling snow, and buffeting winds, mysterious, sinister, scary, wild, deadly, and beastly",
    "Warm tones, Warm hues, A stone house in a sunlit valley, surrounded by forest, A gentle stream meanders into the distance, Peaceful serenity",
    "pop art, wonder woman, 1girl, solo, long hair, black hair, bare shoulders, medium breasts, shield, superhero,simple lines, flat color",
  ],
  [ArtStyle.JojoStyle]: [
    "muscular man, colorful, flexing",
    "woman in long dress, from behind, looking back",
    "cat running away in a market,Shallow depth of field, vignette, highly detailed, high budget, bokeh, Cinemascope, moody, epic, gorgeous",
    "a pianist in the middle of a devastated street, playing a piano on fire, city, buildings",
    "digital painting, aethertech 1930s retro sports car, driving in city, city lights",
  ],
  [ArtStyle.InkBWStyle]: [
    "((joker)), outdoors, gotham, cityscape, raining, smile, wearing a suit",
    "((batman)), cape, black gloves, facial hair, mask, bodysuit, indoors, cave, monitors, tv screens",
    "1girl, solo, cape, sitting on the edge of a cliff, looking down",
    "police officer, 1boy, solo, male focus, sitting in car, police car, badge, star, driving",
  ],
  [ArtStyle.InkSplash]: [
    "1girl, solo, outdoors, black hair, grey eyes, long sleeves, black dress, oil lamps, night time, victorian cityscape, sidewalk, looking at viewer, soft smile, blush, gothic fashion, victorian aesthetic, ((beautiful swirling ink splashes))",
    "1girl, solo, long hair, very long hair, black dress, long sleeves, necklace, jewelry",
    "1girl, solo, indoors, library, bookshelves, wearing a cardigan sweater and glasses, ((beautiful swirling ink splashes))",
    "outdoors, scenery, no humans, forest, (raining, rain), dark, ((beautiful swirling ink splashes))",
  ],
  [ArtStyle.ComicBook]: [
    "1girl, solo, red hair, green eyes, curly hair, cape, black bodysuit, looking at viewer, smile, gotham city, black theme, green theme, cityscape, scenery, rain, gloomy sky, pelting rain, clocktower, railing",
    "((batman)), holding a cat, outdoors in the sunlight",
    "((poison ivy)), 1girl, solo, indoors, brick wall, moss, ivy, potted plants, broken wall, cracked glass, broken windows",
    "outdoors, snowstorm, blizzard, snowing, ((no humans)), scenery, igloo, wind",
    "outdoors, night time, street lamps, ((no humans)), scenery, ((clock tower))",
  ],
  [ArtStyle.InkPunk]: [
    "1girl, solo, sitting by a windowsill, black hair, black eyes, rain, raining, indoors, bedroom, wearing a white shirt and shorts",
    "1girl, solo, upper body, black hair, red eyes, medium hair, messy hair, looking at viewer, disinterested, earrings, jewelry, outside, cityscape, raining, skyscrapers, grey gloomy sky",
    "1boy, solo, male focus, ((spider-man)), (spider web), bodysuit, blue bodysuit, red bodysuit, mask",
    "1boy, solo, male focus, ((batman)), bodysuit, cape, belt, mask, facial hair, long sleeves, black gloves, black cape, skyscraper overlooking a city underneath",
  ],
  [ArtStyle.PaperOrigami]: [
    "bunny, a bunny frolicking in a field of flowers and trees, rabbit",
    "no humans, scenery, outdoors, a field of wheat with a village in the distance, sunset, clouds, warm orange colors, (high quality, highres, 4k, detailed), (paper)",
    "a girl wearing a white long-sleeved dress shopping in a mall, indoors, mall, reflective floor, upper body, portrait, 4k, (paper)",
    "a paper doll wearing a wedding dress, outdoors, sunset, flower petals are falling from the sky",
    "a beach made of paper, blue sky, clouds, waves crashing onto the shore, sand, seashells",
  ],
  [ArtStyle.PixelArt]: [
    "galaxies, stars, no humans, planets, masterpiece, best quality, scenery, beautiful space scenery",
    "1girl, 1boy, outdoors, holding hands, on the moon, a boy and a girl holding hands on the moon, looking over the vast galaxy of stars and nebulas",
    "1girl, solo, holding guitar, playing guitar, black hair, short hair, black eyes, indoors, bedroom, sunset, window, potted plants, hanging potted plants",
    "detailed background, scenery, mystical forest of purple trees, purple magic, purple theme, (white trees, purple trees), ((butterfly, butterflies)), (moon, night sky, night time), no humans",
  ],
  [ArtStyle.AnimeRetroNeon]: [
    "1girl, solo, outdoors, flower field, blue hair, blue eyes, twintails, ((hatsune miku)), smile, looking at viewer",
    "1girl, solo, black hair, (very long hair), hime cut, shirt, tie, black skirt, lace trim, long sleeves, outdoors, space station, stars, galaxies, nebulas, red eyes, blush, smile, looking at viewer",
    "((anime screencap)), 1girl, solo, long hair, looking at viewer, skirt, shirt, red eyes, long sleeves, white hair, pleated skirt, boots, ascot, white skirt, tachi-e, purple footwear, in space station, concrete floor, metal pillars, grate, metal grating, indoors",
    "(1boy, solo, male focus), tie, trench coat, looking at viewer, upper body, smile, brown eyes, short hair, outdoors, scenery, metallic sidewalk, metal sidewalk, moon in the sky, planets, stars, street lamps, sci-fi cityscape, cyberpunk cityscape",
  ],
};
export const RandomTextsNegative: Record<ArtStyle, string[]> = {
  [ArtStyle.AnimeStandard]: ["flare, lens flare, glare, naked, nsfw, text"],
  [ArtStyle.Anime2DFlat]: ["flare, lens flare, glare, naked, nsfw, text"],
  [ArtStyle.AnimeGhibli]: [
    "flare, lens flare, glare,naked, nsfw, text, logo, zombie, sketch, interlocked fingers, comic",
  ],
  [ArtStyle.Cartoon3D]: ["flare, lens flare, glare,naked, nsfw, text, logo"],
  [ArtStyle.Anime2_5D]: ["flare, lens flare, glare,naked, nsfw, text, logo"],
  [ArtStyle.Realistic1]: [
    "3d, cartoon",
    "anime, semi-realistic, painting",
    "bad quality, mutated",
  ],
  [ArtStyle.Realistic2]: [
    "mutated, zombie",
    "3d, cg, render",
    "anime, painting",
  ],
  [ArtStyle.PopArt]: ["flare, lens flare, glare,naked, nsfw, text, logo"],
  [ArtStyle.JojoStyle]: ["flare, lens flare, glare,naked, nsfw, text, logo"],
  [ArtStyle.InkBWStyle]: [
    "3d, render, blender, cg",
    "color, color theme, insert any color you don’t want to see",
    "lowres, blurry",
  ],
  [ArtStyle.InkSplash]: [
    "color, color theme",
    "red, pink",
    "blurry, depth of field",
  ],
  [ArtStyle.ComicBook]: ["realistic, render", "cg, blender", "clothing cutout"],
  [ArtStyle.InkPunk]: [
    "blurry",
    "too many fingers, too many hands",
    "bad anatomy, zombie",
  ],
  [ArtStyle.PaperOrigami]: [
    "realistic, uncanny",
    "flat lighting, uninteresting",
    "wrong color, red color",
  ],
  [ArtStyle.PixelArt]: [
    "simple background, white background",
    "lowres, jpeg artifacts",
    "too many fingers, bad anatomy",
  ],
  [ArtStyle.AnimeRetroNeon]: [
    "looking away, blurry, faceless, from behind",
    "far away, lowres, blurry, monochrome",
    "simple background",
  ],
};
